//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyros.ProductMaster.DataProcess.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataProcessResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataProcessResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyros.ProductMaster.DataProcess.Resource.DataProcessResource", typeof(DataProcessResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @EmailAddress.
        /// </summary>
        internal static string spparam_EmailAddress {
            get {
                return ResourceManager.GetString("spparam_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FirstName.
        /// </summary>
        internal static string spparam_FirstName {
            get {
                return ResourceManager.GetString("spparam_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LastName.
        /// </summary>
        internal static string spparam_LastName {
            get {
                return ResourceManager.GetString("spparam_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MobileNumber.
        /// </summary>
        internal static string spparam_MobileNumber {
            get {
                return ResourceManager.GetString("spparam_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ProductCode.
        /// </summary>
        internal static string spparam_ProductCode {
            get {
                return ResourceManager.GetString("spparam_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ProductId.
        /// </summary>
        internal static string spparam_ProductId {
            get {
                return ResourceManager.GetString("spparam_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ProductUserCode.
        /// </summary>
        internal static string spparam_productUserCode {
            get {
                return ResourceManager.GetString("spparam_productUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ProductUserId.
        /// </summary>
        internal static string spparam_ProductUserId {
            get {
                return ResourceManager.GetString("spparam_ProductUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Kyros].[usp_GetProductUserByProductCode].
        /// </summary>
        internal static string usp_GetProductUserByProductCode {
            get {
                return ResourceManager.GetString("usp_GetProductUserByProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Kyros].[usp_GetProductUserByProductId].
        /// </summary>
        internal static string usp_GetProductUserByProductId {
            get {
                return ResourceManager.GetString("usp_GetProductUserByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Kyros].[usp_GetProductUserByProductUserId].
        /// </summary>
        internal static string usp_GetProductUserByProductUserId {
            get {
                return ResourceManager.GetString("usp_GetProductUserByProductUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Kyros].[usp_ManageProductUser].
        /// </summary>
        internal static string usp_ManageProductUser {
            get {
                return ResourceManager.GetString("usp_ManageProductUser", resourceCulture);
            }
        }
    }
}
